name = "fireplanner"
pages_build_output_dir = "dist"
compatibility_date = "2026-02-01"

[[d1_databases]]
binding = "DB"
database_name = "sgfire-emails"
database_id = "01e9163d-72f1-4d0e-894c-3af94c941f21"
